name: action-log

on:
  # Trigger the action on these events
  pull_request:
    types:
      - synchronize
      - opened
      - ready_for_review
      - reopened
  pull_request_review:
    types:
      - submitted
  check_suite:
    types:
      - completed

jobs:
  action-log:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: ./
